# Generated by Django 3.2.4 on 2021-07-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food',
            table='foods',
        ),
        migrations.AlterModelTable(
            name='foodcategory',
            table='foods_categories',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderdescription',
            table='orders_description',
        ),
    ]
